name: Linting

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  Black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./src ./tests"
  Ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install ruff
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff
      - name: Run ruff
        run: |
          ruff src
  MyPy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install MyPy
        run: |
          python -m pip install --upgrade pip
          python -m pip install mypy
      - name: Run MyPy
        run: |
          mypy src
