name: Linting

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Project
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[lint]
      - name: Run Black
        if: always()
        run: |
          black --check --verbose src tests
      - name: Run Ruff
        if: always()
        run: |
          ruff check src
      - name: Run MyPy
        if: always()
        run: |
          mypy src
